---
title: "Descriptive Statistics"
author: "Chunyen"
date: "2024/3/13"
output: 
  pdf_document:
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{Noto Sans CJK TC}
---

# Introduction

描述性統計自殺風險等級、逐字稿、參照句子

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r include=FALSE}
# import libraries
library(tidyverse)

```

```{r}
# set working directory
setwd("/home/quantlab/2024_ChunyenThesis/Bert")
```

```{r include=FALSE}
# Fix the Mandarin font issue
library(showtext)

# 添加字體
# font_add("Noto Sans CJK TC", "/usr/share/fonts/opentype/noto/NotoSansCJK-Light.ttc")
font_add("Noto Sans CJK TC", "/notebooks/exploratory/NotoSansCJK-Light.ttc")

# 啟用 showtext_auto() 自動渲染文字
showtext_auto()

```

```{r}
# Set folder path
processed_path <- "data/processed/"
# refSentences_path = "data/rawdata/ref_sentences/"

```

# 自殺風險等級

`risklevel.csv` 的架構

```{r include=FALSE}
risklevel_tib <- read_csv(paste0(processed_path, "risklevel.csv"))
```

```{r}
risklevel_tib %>% str()
```

## 逐字稿年份分佈

```{r}
# plot
risklevel_tib %>% 
  mutate(year = dialogue_id %>% substr(., 1, 4)) %>% 
  count(year) %>%
  ggplot(aes(x = year, y = n)) +
  geom_col() +
  labs(title = "逐字稿年份分佈", x = "年份", y = "逐字稿數量") +
  # 加上數值
  geom_text(aes(label = n), vjust = -0.5, size = 3) +
  theme_minimal() +
  theme(text = element_text(family = "Noto Sans CJK TC"))
```

## 自殺風險各等級分布

```{r}
# risk_level
risklevel_tib %>% 
  count(risk_level) %>%
  ggplot(aes(x = risk_level, y = n)) +
  geom_col() +
  labs(title = "原始自殺風險各等級分布", x = "風險等級", y = "逐字稿數量") +
  # 加上數值
  geom_text(aes(label = n), vjust = -0.5, size = 3) +
  theme_minimal() +
  theme(text = element_text(family = "Noto Sans CJK TC"))

# risk5
risklevel_tib %>% 
  count(risk5) %>%
  ggplot(aes(x = risk5, y = n)) +
  geom_col() +
  labs(title = "自殺風險等級5分布", x = "風險等級5", y = "逐字稿數量") +
  # 加上數值
  geom_text(aes(label = n), vjust = -0.5, size = 3) +
  theme_minimal() +
  theme(text = element_text(family = "Noto Sans CJK TC"))

# risk4
risklevel_tib %>% 
  count(risk4) %>%
  ggplot(aes(x = risk4, y = n)) +
  geom_col() +
  labs(title = "自殺風險等級4分布", x = "風險等級4", y = "逐字稿數量") +
  # 加上數值
  geom_text(aes(label = n), vjust = -0.5, size = 3) +
  theme_minimal() +
  theme(text = element_text(family = "Noto Sans CJK TC"))

# risk3
risklevel_tib %>% 
  count(risk3) %>%
  ggplot(aes(x = risk3, y = n)) +
  geom_col() +
  labs(title = "自殺風險等級3分布", x = "風險等級3", y = "逐字稿數量") +
  # 加上數值
  geom_text(aes(label = n), vjust = -0.5, size = 3) +
  theme_minimal() +
  theme(text = element_text(family = "Noto Sans CJK TC"))
```

# 逐字稿

## 只有求助者的發言語句

### `transcripts_emb_caller.csv` 的架構

```{r include=FALSE}
# read data
transcript_caller_tib <- read_csv(paste0(processed_path, "transcripts_emb_caller.csv"))
```

```{r}
transcript_caller_tib %>% str()
```

### 總字數、語句數

```{r results='asis'}
# add all the value of the columns `utterance_len`
wordCount = transcript_caller_tib %>% select(utterance_len) %>% sum()
sprintf("逐字稿共有 %s 個字", wordCount)
```


```{r results='asis'}
# row len
utCount = transcript_caller_tib %>% nrow()
sprintf("逐字稿共有 %s 個語句", utCount)
```


```{r results='asis'}
# average words in one utterance
sprintf("每個語句平均有 %s 個字", wordCount/utCount)

```

### 各發言語句中，發言的字數描述統計

```{r}
# describe 
transcript_caller_tib %>% 
  select(utterance_len) %>%
  as.data.frame() %>% 
  psych::describe() %>% 
  round(2) %>% 
  knitr::kable()
```

### 各逐字稿中，發言的語句數分配

```{r}
# describe
transcript_caller_tib %>% 
  count(dialogue_id) %>%
  select(n) %>%
  as.data.frame() %>% 
  psych::describe() %>% 
  round(2) %>%
  knitr::kable()

# distribution
transcript_caller_tib %>% 
  count(dialogue_id) %>%
  ggplot(aes(x = n)) +
  geom_histogram(binwidth = 1) +
  labs(title = "逐字稿中，求助者發言的語句數分配", x = "語句數", y = "逐字稿數量") +
  theme_minimal() +
  theme(text = element_text(family = "Noto Sans CJK TC"))+
  scale_y_continuous(breaks = seq(0, 10, 5), labels = seq(0, 10, 5))

# 依照 100 語句為一組，逐字稿數量
transcript_caller_tib %>% 
  count(dialogue_id) %>% 
  mutate(group = n %/% 100) %>%
  count(group) %>%
  ggplot(aes(x = group, y = n)) +
  geom_col() +
  labs(title = "逐字稿中，求助者發言的語句數分配", x = "語句數", y = "逐字稿數量") +
  theme_minimal() +
  theme(text = element_text(family = "Noto Sans CJK TC")) +
  # 修改 x 軸的 level 名稱
  scale_x_continuous(breaks = seq(0, 10, 5), labels = seq(0, 10, 5) * 100) +
  # 加上數值
  geom_text(aes(label = n), vjust = -0.5, size = 3)
  
```

### 各逐字稿中，發言的總字數分配

```{r}
# describe
transcript_caller_tib %>% 
  group_by(dialogue_id) %>% 
  summarise(n = sum(utterance_len)) %>% 
  select(n) %>%
  as.data.frame() %>% 
  psych::describe() %>% 
  round(2) %>%
  knitr::kable()

# distribution
transcript_caller_tib %>% 
  group_by(dialogue_id) %>% 
  summarise(n = sum(utterance_len)) %>% 
  ggplot(aes(x = n)) +
  geom_histogram(binwidth = 100) +
  labs(title = "逐字稿中，求助者發言的總字數分配", x = "字數", y = "逐字稿數量") +
  theme_minimal() +
  theme(text = element_text(family = "Noto Sans CJK TC"))+
  scale_y_continuous(breaks = seq(0, 10, 5), labels = seq(0, 10, 5))

# 依照 1000 字為一組，逐字稿數量
transcript_caller_tib %>% 
  group_by(dialogue_id) %>% 
  summarise(n = sum(utterance_len)) %>% 
  mutate(group = n %/% 1000) %>%
  count(group) %>%
  ggplot(aes(x = group, y = n)) +
  geom_col() +
  labs(title = "逐字稿中，發言的總字數分配", x = "字數", y = "逐字稿數量") +
  theme_minimal() +
  theme(text = element_text(family = "Noto Sans CJK TC")) +
  # 修改 x 軸的 level 名稱
  scale_x_continuous(breaks = seq(0, 10, 5), labels = seq(0, 10, 5) * 1000) +
  # 加上數值
  geom_text(aes(label = n), vjust = -0.5, size = 3)

```

## 只有接線員的發言語句

### `transcripts_emb_operator.csv` 的架構

```{r include=FALSE}
# read data
transcript_responser_tib <- read_csv(paste0(processed_path, "transcripts_emb_responser.csv"))
```

```{r}
transcript_responser_tib %>% str()
```

### 總字數、語句數

```{r results='asis'}
# add all the value of the columns `utterance_len`
wordCount = transcript_responser_tib %>% select(utterance_len) %>% sum()
sprintf("逐字稿共有 %s 個字", wordCount)
```

```{r results='asis'}
# row len
utCount = transcript_responser_tib %>% nrow()
sprintf("逐字稿共有 %s 個語句", utCount)
```

```{r results='asis'}
# average words in one utterance
sprintf("每個語句平均有 %s 個字", wordCount/utCount)
```

### 各發言語句中，發言的字數描述統計

```{r}
# describe
transcript_responser_tib %>% 
  select(utterance_len) %>%
  as.data.frame() %>% 
  psych::describe() %>% 
  round(2) %>% 
  knitr::kable()

```

### 各逐字稿中，發言的語句數分配

```{r}
# describe
transcript_responser_tib %>% 
  count(dialogue_id) %>%
  select(n) %>%
  as.data.frame() %>% 
  psych::describe() %>% 
  round(2) %>%
  knitr::kable()

# distribution
transcript_responser_tib %>% 
  count(dialogue_id) %>%
  ggplot(aes(x = n)) +
  geom_histogram(binwidth = 1) +
  labs(title = "逐字稿中，接線員發言的語句數分配", x = "語句數", y = "逐字稿數量") +
  theme_minimal() +
  theme(text = element_text(family = "Noto Sans CJK TC"))+
  scale_y_continuous(breaks = seq(0, 10, 5), labels = seq(0, 10, 5))

# 依照 100 語句為一組，逐字稿數量
transcript_responser_tib %>% 
  count(dialogue_id) %>% 
  mutate(group = n %/% 100) %>%
  count(group) %>%
  ggplot(aes(x = group, y = n)) +
  geom_col() +
  labs(title = "逐字稿中，接線員發言的語句數分配", x = "語句數", y = "逐字稿數量") +
  theme_minimal() +
  theme(text = element_text(family = "Noto Sans CJK TC")) +
  # 修改 x 軸的 level 名稱
  scale_x_continuous(breaks = seq(0, 10, 5), labels = seq(0, 10, 5) * 100) +
  # 加上數值
  geom_text(aes(label = n), vjust = -0.5, size = 3)
  
```

### 各逐字稿中，發言的總字數分配

```{r}
# describe
transcript_responser_tib %>% 
  group_by(dialogue_id) %>% 
  summarise(n = sum(utterance_len)) %>% 
  select(n) %>%
  as.data.frame() %>% 
  psych::describe() %>% 
  round(2) %>%
  knitr::kable()

# distribution
transcript_responser_tib %>% 
  group_by(dialogue_id) %>% 
  summarise(n = sum(utterance_len)) %>% 
  ggplot(aes(x = n)) +
  geom_histogram(binwidth = 100) +
  labs(title = "逐字稿中，接線員發言的總字數分配", x = "字數", y = "逐字稿數量") +
  theme_minimal() +
  theme(text = element_text(family = "Noto Sans CJK TC"))+
  scale_y_continuous(breaks = seq(0, 10, 5), labels = seq(0, 10, 5))

# 依照 1000 字為一組，逐字稿數量
transcript_responser_tib %>% 
  group_by(dialogue_id) %>% 
  summarise(n = sum(utterance_len)) %>% 
  mutate(group = n %/% 1000) %>%
  count(group) %>%
  ggplot(aes(x = group, y = n)) +
  geom_col() +
  labs(title = "逐字稿中，接線員發言的總字數分配", x = "字數", y = "逐字稿數量") +
  theme_minimal() +
  theme(text = element_text(family = "Noto Sans CJK TC")) +
  # 修改 x 軸的 level 名稱
  scale_x_continuous(breaks = seq(0, 10, 5), labels = seq(0, 10, 5) * 1000) +
  # 加上數值
  geom_text(aes(label = n), vjust = -0.5, size = 3)
```


# 參照句子

- 合併量表（自殺危險程度量表＋自殺意念量表）
- 自殺意念量表（BSS）
- 自殺危險程度量表
- 自殺辭典

```{r}
refSentencesCsv_vec <- c(
  'BSS_suicidalRisk_scale.csv', 'BSS_scale.csv', 'suicidalRisk_scale.csv', 'Lv_suicide_dict.csv') # 合併量表、自殺意念量表、自殺危險程度量表、自殺辭典

refSentecesEmbCsv_vec <- c("refSentences1_emb.csv", "refSentences2_emb.csv", "refSentences3_emb.csv", "refSentences4_emb.csv")
```

```{r include=FALSE}
# read data
refSentences1_tib <- read_csv(paste0(processed_path, "refSentences1_emb.csv"))
refSentences2_tib <- read_csv(paste0(processed_path, "refSentences2_emb.csv"))
refSentences3_tib <- read_csv(paste0(processed_path, "refSentences3_emb.csv"))
refSentences4_tib <- read_csv(paste0(processed_path, "refSentences4_emb.csv"))
```

## 題數

```{r results='asis'}
sprintf("合併量表題數：%s 題", refSentences1_tib %>% nrow())
```
```{r results='asis'}
sprintf("自殺意念量表：%s 題", refSentences2_tib %>% nrow())
```
```{r results='asis'}
sprintf("自殺危險程度量表：%s 題", refSentences3_tib %>% nrow())
```
```{r results='asis'}
sprintf("自殺詞典：%s 個詞", refSentences4_tib %>% nrow())
```




## 字元數

```{r}
wordCountRef1 <- refSentences1_tib %>% 
  mutate(len = text %>% nchar()) %>% 
  pull(len) %>% 
  sum()
wordCountRef2 <- refSentences2_tib %>% 
  mutate(len = text %>% nchar()) %>% 
  pull(len) %>% 
  sum()
wordCountRef3 <- refSentences3_tib %>% 
  mutate(len = text %>% nchar()) %>% 
  pull(len) %>% 
  sum()
wordCountRef4 <- refSentences4_tib %>% 
  mutate(len = text %>% nchar()) %>% 
  pull(len) %>% 
  sum()
```

```{r results='asis'}
sprintf("合併量表總字元數：%s 字", wordCountRef1)
```
```{r results='asis'}
sprintf("自殺意念量表總字元數：%s 字", wordCountRef2)
```
```{r results='asis'}
sprintf("自殺危險程度量表總字元數：%s 字", wordCountRef3)
```
```{r results='asis'}
sprintf("自殺詞典總字元數：%s 字", wordCountRef4)
```

