---
title: "Visualization of Model Predicting Cumulative Utterances (Predicted Label heatmap)"
author: "Chunyen"
date: "2024/3/24"
output: 
  pdf_document:
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{Noto Sans CJK TC}
---

# Introduction

視覺化逐句累積輸入時模型預測的模型預測類別。

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r include=FALSE}
# import libraries
library(tidyverse)
library(ggplot2)
library(yardstick)
library(reshape2)
library(scales)
```

```{r}
# set working directory
setwd("/home/quantlab/2024_ChunyenThesis/Bert")
```

```{r include=FALSE}
# Fix the Mandarin font issue
library(showtext)

# 添加字體
# font_add("Noto Sans CJK TC", "/usr/share/fonts/opentype/noto/NotoSansCJK-Light.ttc")
font_add("Noto Sans CJK TC", "/notebooks/exploratory/NotoSansCJK-Light.ttc")

# 啟用 showtext_auto() 自動渲染文字
showtext_auto()

```

# Function

```{r}
# Function

# Read predict label data
Read_predict_label <- function(risklevel, refSentence, allFilesName_vec, foldpath){
  filteredFilesName <- allFilesName_vec[grep(risklevel, allFilesName_vec)]
  filteredFilesName <- filteredFilesName[grep(refSentence, filteredFilesName)]
  filteredFilesName <- filteredFilesName[grep("predict_label", filteredFilesName)]
  # It should be only one file
  input_tib <- read_csv(paste0(foldpath, "/", filteredFilesName))
  return(input_tib)
}
# Read predict metric data
Read_predict_metric <- function(risklevel, refSentence, allFilesName_vec, foldpath){
  filteredFilesName <- allFilesName_vec[grep(risklevel, allFilesName_vec)]
  filteredFilesName <- filteredFilesName[grep(refSentence, filteredFilesName)]
  filteredFilesName <- filteredFilesName[grep("predict_metric", filteredFilesName)]
  # It should be only one file
  input_tib <- read_csv(paste0(foldpath, "/", filteredFilesName))
  return(input_tib)
}

Plot_heatmap <- function(data, title, risklevel){
  level_num <- sub("risk", "", risklevel) %>% as.integer()

  # 計算每個 cum_ut 和 y_pred 組合的頻率
  data$freq <- ave(data$y_pred, list(data$cum_ut, data$y_pred), FUN=length)
  
  # 將 y_pred 轉換為因子型態，因為它是類別變項
  data$y_pred <- as.factor(data$y_pred)
  
  # 轉換數據為適合熱力圖的格式
  data_melted <- melt(data, id.vars=c("cum_ut", "y_pred"), measure.vars="freq")
  
  # 計算總頻率以便轉換為百分比
  total_freq <- data$dialogue_id %>% unique() %>% length()
  
  title <- sprintf("%s (n = %s)", title, total_freq)
  
  p <- ggplot(data_melted, aes(x=cum_ut, y=y_pred, fill=value/total_freq)) +
    geom_tile() +
    scale_fill_gradient(low="lightgrey", high="black", labels=label_percent(), limits=c(0, 1)) +
    labs(x="Cumulative Utterance Count", y="Predicted Label", fill="Percentage", title = title) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_x_continuous(breaks=seq(0, 1000, 100), limits=c(0, 1000))
  
  print(p)
}
```



```{r}
# Set folder path
processed_path <- "data/processed/"
rfReports_path <- "results/rf_cum_utterance"
bertReports_path <- "results/bert_cum_utterance"

rf_allFilesName_vec <- list.files(rfReports_path, pattern = "\\.csv$", full.names = TRUE) %>% basename()
bert_allFilesName_vec <- list.files(bertReports_path, pattern = "\\.csv$", full.names = TRUE) %>% basename()

```

```{r include=FALSE}
# read transcript and risklevel data
risklevel_tib <- read_csv(paste0(processed_path, "risklevel.csv"))
transcript_caller_tib <- read_csv(paste0(processed_path, "transcripts_emb_caller.csv"))
transcript_responser_tib <- read_csv(paste0(processed_path, "transcripts_emb_responser.csv"))

# Count utterances by each dialogue_id
utNum_caller_tib <- transcript_caller_tib %>% 
  group_by(dialogue_id) %>%
  summarise(utNum_caller = n())
utNum_responser_tib <- transcript_responser_tib %>% 
  group_by(dialogue_id) %>%
  summarise(utNum_responser = n())

# join by dialogue_id
utNum_tib <- utNum_caller_tib %>% 
  left_join(., utNum_responser_tib, by = "dialogue_id")
data_tib <- risklevel_tib %>% 
  left_join(., utNum_tib, by = "dialogue_id")

# Group transcripts by utterance number of caller
cut_off1 <- 150
cut_off2 <- 300
data_tib <- data_tib %>% 
  mutate(utNum_caller_group = case_when(
    utNum_caller <= cut_off1 ~ "short",
    utNum_caller > cut_off1 & utNum_caller <= cut_off2 ~ "medium",
    utNum_caller > cut_off2 ~ "long"
  ))
# Group transcripts by utterance number of responser
cut_off1 <- 175
cut_off2 <- 350
data_tib <- data_tib %>% 
  mutate(utNum_responser_group = case_when(
    utNum_responser <= cut_off1 ~ "short",
    utNum_responser > cut_off1 & utNum_responser <= cut_off2 ~ "medium",
    utNum_responser > cut_off2 ~ "long"
  ))

groupDialogue_tib <- data_tib %>% 
  select(dialogue_id, utNum_caller_group, utNum_responser_group)
```



# Risk3 X RF Model

```{r include=FALSE}
risklevel <- "risk3"
refSentence <- "max_sim_ref3"
# read cumulative utterance predicted label data
rf_label_tib <- Read_predict_label(risklevel, refSentence, rf_allFilesName_vec, rfReports_path)
```

```{r}
rf_label_tib %>% 
  Plot_heatmap("RF Model Predicted Label Over Cumulative Utterances", risklevel)
```

## groupby utterance number

```{r}
g1 <- rf_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(utNum_caller_group == "short") %>%
  Plot_heatmap("短語句組", risklevel)
g2 <- rf_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(utNum_caller_group == "medium") %>%
  Plot_heatmap("中語句組", risklevel)
g3 <- rf_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(utNum_caller_group == "long") %>%
  Plot_heatmap("長語句組", risklevel)

gridExtra::grid.arrange(g1, g2, g3, ncol = 1, nrow = 3,
                        top = "RF Model Predicted Label Over Cumulative Utterances (Risk3)"
                        )
```

## groupby risk level
```{r}
g4 <- rf_label_tib %>%
  filter(risk3 == 2) %>%
  Plot_heatmap("Risk = 2", risklevel)
g5 <- rf_label_tib %>%
  filter(risk3 == 1) %>%
  Plot_heatmap("Risk = 1", risklevel)
g6 <- rf_label_tib %>%
  filter(risk3 == 0) %>%
  Plot_heatmap("Risk = 0", risklevel)

gridExtra::grid.arrange(g4, g5, g6, ncol = 1, nrow = 3,
                        top = "RF Model Predicted Label Over Cumulative Utterances (Risk3)"
                        )
```

## group by risk level and utterance number
```{r}
g7 <- rf_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 2 & utNum_caller_group == "short") %>%
  Plot_heatmap("Risk = 2, 短語句組", risklevel)
g8 <- rf_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 2 & utNum_caller_group == "medium") %>%
  Plot_heatmap("Risk = 2, 中語句組", risklevel)
g9 <- rf_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 2 & utNum_caller_group == "long") %>%
  Plot_heatmap("Risk = 2, 長語句組", risklevel)

gridExtra::grid.arrange(g7, g8, g9, ncol = 1, nrow = 3,
                        top = "RF Model Predicted Label Over Cumulative Utterances (Risk3)"
                        )

g10 <- rf_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 1 & utNum_caller_group == "short") %>%
  Plot_heatmap("Risk = 1, 短語句組", risklevel)
g11 <- rf_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 1 & utNum_caller_group == "medium") %>%
  Plot_heatmap("Risk = 1, 中語句組", risklevel)
g12 <- rf_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 1 & utNum_caller_group == "long") %>%
  Plot_heatmap("Risk = 1, 長語句組", risklevel)

gridExtra::grid.arrange(g10, g11, g12, ncol = 1, nrow = 3,
                        top = "RF Model Predicted Label Over Cumulative Utterances (Risk3)"
                        )

g13 <- rf_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 0 & utNum_caller_group == "short") %>%
  Plot_heatmap("Risk = 0, 短語句組", risklevel)
g14 <- rf_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 0 & utNum_caller_group == "medium") %>%
  Plot_heatmap("Risk = 0, 中語句組", risklevel)
g15 <- rf_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 0 & utNum_caller_group == "long") %>%
  Plot_heatmap("Risk = 0, 長語句組", risklevel)

gridExtra::grid.arrange(g13, g14, g15, ncol = 1, nrow = 3,
                        top = "RF Model Predicted Label Over Cumulative Utterances (Risk3)"
                        )

```

# Risk3 X BERT Model

```{r include=FALSE}
risklevel <- "risk3"
refSentence <- "max_sim_ref1"
# read cumulative utterance predicted label data
bert_label_tib <- Read_predict_label(risklevel, refSentence, bert_allFilesName_vec, bertReports_path)
```


```{r}
bert_label_tib %>% 
  Plot_heatmap("BERT Model Predicted Label Over Cumulative Utterances", risklevel)
```

## groupby utterance number

```{r}
g1 <- bert_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(utNum_caller_group == "short") %>%
  Plot_heatmap("短語句組", risklevel)
g2 <- bert_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(utNum_caller_group == "medium") %>%
  Plot_heatmap("中語句組", risklevel)
g3 <- bert_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(utNum_caller_group == "long") %>%
  Plot_heatmap("長語句組", risklevel)

gridExtra::grid.arrange(g1, g2, g3, ncol = 1, nrow = 3,
                        top = "BERT Model Predicted Label Over Cumulative Utterances (Risk3)"
                        )
```

## groupby risk level
```{r}
g4 <- bert_label_tib %>%
  filter(risk3 == 2) %>%
  Plot_heatmap("Risk = 2", risklevel)
g5 <- bert_label_tib %>%
  filter(risk3 == 1) %>%
  Plot_heatmap("Risk = 1", risklevel)
g6 <- bert_label_tib %>%
  filter(risk3 == 0) %>%
  Plot_heatmap("Risk = 0", risklevel)

gridExtra::grid.arrange(g4, g5, g6, ncol = 1, nrow = 3,
                        top = "BERT Model Predicted Label Over Cumulative Utterances (Risk3)"
                        )
```

## group by risk level and utterance number
```{r}
g7 <- bert_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 2 & utNum_caller_group == "short") %>%
  Plot_heatmap("Risk = 2, 短語句組", risklevel)
g8 <- bert_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 2 & utNum_caller_group == "medium") %>%
  Plot_heatmap("Risk = 2, 中語句組", risklevel)
g9 <- bert_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 2 & utNum_caller_group == "long") %>%
  Plot_heatmap("Risk = 2, 長語句組", risklevel)

gridExtra::grid.arrange(g7, g8, g9, ncol = 1, nrow = 3,
                        top = "BERT Model Predicted Label Over Cumulative Utterances (Risk3)"
                        )

g10 <- bert_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 1 & utNum_caller_group == "short") %>%
  Plot_heatmap("Risk = 1, 短語句組", risklevel)
g11 <- bert_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 1 & utNum_caller_group == "medium") %>%
  Plot_heatmap("Risk = 1, 中語句組", risklevel)
g12 <- bert_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 1 & utNum_caller_group == "long") %>%
  Plot_heatmap("Risk = 1, 長語句組", risklevel)

gridExtra::grid.arrange(g10, g11, g12, ncol = 1, nrow = 3,
                        top = "BERT Model Predicted Label Over Cumulative Utterances (Risk3)"
                        )

g13 <- bert_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 0 & utNum_caller_group == "short") %>%
  Plot_heatmap("Risk = 0, 短語句組", risklevel)
g14 <- bert_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 0 & utNum_caller_group == "medium") %>%
  Plot_heatmap("Risk = 0, 中語句組", risklevel)
g15 <- bert_label_tib %>%
  left_join(., groupDialogue_tib, by = "dialogue_id") %>%
  filter(risk3 == 0 & utNum_caller_group == "long") %>%
  Plot_heatmap("Risk = 0, 長語句組", risklevel)

gridExtra::grid.arrange(g13, g14, g15, ncol = 1, nrow = 3,
                        top = "BERT Model Predicted Label Over Cumulative Utterances (Risk3)"
                        )
```

