---
title: "Visualization of Cumulative Utterances' `utterance_id`"
author: "Chunyen"
date: "2024/3/23"
output: 
  pdf_document:
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{Noto Sans CJK TC}
---

# Introduction

視覺化逐句累積輸入時關鍵句的變化，

使用語句位置的編號`utterance_id`表示。

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r include=FALSE}
# import libraries
library(tidyverse)
library(ggplot2)
```

```{r}
# set working directory
setwd("/home/quantlab/2024_ChunyenThesis/Bert")
```

```{r include=FALSE}
# Fix the Mandarin font issue
library(showtext)

# 添加字體
# font_add("Noto Sans CJK TC", "/usr/share/fonts/opentype/noto/NotoSansCJK-Light.ttc")
font_add("Noto Sans CJK TC", "/notebooks/exploratory/NotoSansCJK-Light.ttc")

# 啟用 showtext_auto() 自動渲染文字
showtext_auto()

```

```{r}
# 數據導入
path <- "data/processed/cum_utterance_id_test.csv"
data_df <- read.csv(path)

# 使用迴圈逐篇對話繪製關鍵句的變化圖
dialogue_ids <- unique(data_df$dialogue_id)

transcript_df <- read.csv("data/processed/transcripts_caller.csv")
transcript_test_df <-
  transcript_df %>% 
  filter(dialogue_id %in% dialogue_ids)
# 計算每一篇逐字稿的語句數量
ut_num_df <- transcript_test_df %>% 
  group_by(dialogue_id) %>%
  summarise(utterance_num = n())
# 選擇各篇最大的 utterance_id
ut_maxID_df <- data_df %>% 
  group_by(dialogue_id) %>%
  summarise(max_utterance_id = max(utterance_id))

dia_num <- length(unique(data_df$dialogue_id))

# 數據轉換為長格式
data_long <- data_df %>%
  # 新增一欄位表示語序的排序 1-10
  mutate(utterance_order = rep(1:10, dia_num)) %>% 
  gather(
    key = "cumulative_step", 
    value = "selected_utterance_id", 
    -dialogue_id, -risk3, -utterance_id, -utterance_order) %>%
  mutate(cumulative_step = as.integer(gsub("utterance_id", "", cumulative_step))) %>%
  arrange(dialogue_id, cumulative_step)

for(did in dialogue_ids) {
  
  # print(paste("Plotting for Dialogue ID:", did))
  
  # 篩選出該對話ID的數據
  data_subset <- data_long %>% filter(dialogue_id == did)
  
  # 該篇逐字稿語句數
  ut_num <- ut_num_df$utterance_num[ut_num_df$dialogue_id == did]
  # 該篇最大的 utterance_id
  ut_maxID <- ut_maxID_df$max_utterance_id[ut_maxID_df$dialogue_id == did]

  # 繪製圖表
  p <- data_subset %>% 
    ggplot(., aes(x = cumulative_step, y = selected_utterance_id, group = utterance_order, color = as.factor(utterance_order))) +
  # geom_line() + # 繪製線條
  geom_point() + # 繪製點
  theme_minimal() + # 使用簡潔主題
  labs(
    title = paste("DID:", did, "(", ut_num, "utterances, max UID:", ut_maxID, ")"),
       x = "Cumulative Step",
       y = "Selected Utterance ID",
       color = "Utterance Order") + # 設置標籤
  scale_color_viridis_d(guide = FALSE) + # 使用viridis色彩，不顯示圖例
  theme(legend.position = "none") + # 不顯示圖例
  scale_x_continuous(breaks = seq(0, 1000, 100), limits = c(0, 1000)) # 設置x軸
  
  print(p)
  
  # Sys.sleep(1)
}

```

